name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: "http://yourblog-domain.com"
google_analytics: "G-D66T2K2YCV"
#"UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Ju Gamdong"

# Disqus config
disqus-shortname: "myAssign"
# Analytics
analytics:
  provider               : "google" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-D66T2K2YCV"
    anonymize_ip         : # true, false (default)