name: Eureka Jekyll Site
description: Blogging about Eureka
meta_description: "Eureka Jekyll Site, Blogging about Eureka"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: 
domain_name: "https://jjthis.github.io/"
google_analytics: "G-D66T2K2YCV"
#"UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: "https://jjthis.github.io/"
author: "Ju Gamdong"

# Disqus config
disqus-shortname: "myAssign"
# Analytics
analytics:
  provider               : "google" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-D66T2K2YCV"
    anonymize_ip         : # true, false (default)